alphabet_size: 40
args: !!python/object:argparse.Namespace
  batch_size: 32
  ckpt_iterations: null
  cls_ckpt: null
  dropout: 0.1
  expand_simplex: true
  flow_type: argmax
  hidden_dim: 512
  limit_train_batches: 1000
  limit_val_batches: 1000
  max_epochs: 5000
  num_cnn_stacks: 5
  num_integration_steps: 10
  num_workers: 4
  prior_pseudocount: 2
  shuffle: false
  toy_num_cls: 1
  toy_seq_len: 4
  toy_simplex_dim: 40
num_cls: 1
toy_data: !!python/object:datasets.ToyDataset
  alphabet_size: 40
  class_probs: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCgAAADExNTc2MTQzMzZxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAxMTU3NjE0
      MzM2cQFhLgEAAAAAAAAAAACAPw==
  - 0
  - !!python/tuple
    - 1
  - !!python/tuple
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  max_samples: 512000
  num_cls: 1
  probs: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCgAAADExMzAyMDAzNTJxAlgDAAAAY3B1cQNLoE50cQRRLoACXXEAWAoAAAAxMTMwMjAw
      MzUycQFhLqAAAAAAAAAATJ7OPNxIqzyw6QA978aCPMLHkjwTGgM9l+vdPLvekzxNmtc8CI6WPFZ9
      Iz2wyqA8/OPXPNvk/zwyOhA9PVEKPb44uDwAMNQ8X8KxPDsfkDyTU8w8OLq4PEwVlDwsiZg8en2k
      PDlNijz+kyI93dXqPGzBvzwcVo08txO0PLp21jzdegE9Lu/tPCgPiTwiAac8VQ4APQS2yTyVBdc8
      Kd4NPV++5TwtzZ889UWgPFwhjTzQEd086p4hPaZr1Dye9bQ8ndK1PK3L8TzE4aA8cQkqPTBruzyp
      VYs8TfHIPH62CD2hvCs9qCPAPPmxKz3yuto8XN6HPNDA0zyk3ao8p1GXPM374DyfYdY86RCTPKjp
      jjwJ/8U8yjWvPCk2wzzHWOc8xkCVPKvNDz0PXI0806KVPL4KrDxUfMA8O9gAPXbxvjzA+gA9DBGA
      PK/Oizw69eU8XflyPO6O0Twi9uo8CmyHPDjcxzyn3Yo8sGIAPcqTBz18src8ueN8PP61uzxFH5Y8
      gqMePUBWjTzMqBg9K1yRPL7/oDxieMA833zsPGUxuTwTQc08VJv2PEow8zww0Nk8VNK4PGORAz0s
      zJY85IytPBwcDz2R7sk8VreFPHmgCj0XwBg9wXOpPFICwjzEOg09ST/RPPnR9Dwibto8NKjnPAwG
      mzxhOcE8EWWzPOwAFT0d/Hw8SU2ePE6Y2jyfwas8irmRPBjqgjz+S+o87CL8PP4mDz3cEpo8aQz3
      PI5dED0ynxU9sYzvPIJRljwDtWg8aJEbPbdJrjxC7r88c4CKPAVOlzx+AIo8sX8PPW9fkzyVRNI8
      V4OlPMXD2DzDMqw8STvOPLGfljxpjhM9CQ4PPQ==
  - 0
  - !!python/tuple
    - 1
    - 4
    - 40
  - !!python/tuple
    - 160
    - 40
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  seq_len: 4
