alphabet_size: 40
args: !!python/object:argparse.Namespace
  batch_size: 32
  ckpt_iterations: null
  cls_ckpt: null
  dropout: 0.1
  expand_simplex: true
  flow_type: argmax
  hidden_dim: 512
  limit_train_batches: 1000
  limit_val_batches: 1000
  max_epochs: 5000
  num_cnn_stacks: 5
  num_integration_steps: 10
  num_workers: 4
  prior_pseudocount: 2
  shuffle: false
  toy_num_cls: 1
  toy_seq_len: 4
  toy_simplex_dim: 40
num_cls: 1
toy_data: !!python/object:datasets.ToyDataset
  alphabet_size: 40
  class_probs: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCQAAADY4NTY5MzUzNnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADY4NTY5MzUz
      NnEBYS4BAAAAAAAAAAAAgD8=
  - 0
  - !!python/tuple
    - 1
  - !!python/tuple
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  max_samples: 512000
  num_cls: 1
  probs: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCQAAADY1NTM0MDMzNnECWAMAAABjcHVxA0ugTnRxBFEugAJdcQBYCQAAADY1NTM0MDMz
      NnEBYS6gAAAAAAAAAHu5Dj043Ic85XPcPIOK5jxH34Q8DlfKPNM1gTyS44k8jlOjPAZ5hDx/WAg9
      1FoAPf76rTxOIcA8sakUPT92oTxMZac8TFJ2PGQMyjwlsLA8VLSpPH51yDwicuk86T0IPfYXejwk
      4qA8CtrxPJ87vjzBKiQ9/b6qPBR78zyR8b48NvbBPC/fCD2H6Rc9O2D/PBJHBD01IYg8YzboPEmU
      0jzy0NY8QZ35PCSbejzAMAk97XUNPQHCeDzy2eo8/1+TPATsgzxHJIc8O4SOPPMNozxXErU8h63X
      PKHRED2sgY88Iy2BPLGp1Tx/apU8+lWhPP3EtjzXIbg8OJfJPCgWjjyFYYA8WbgRPer/gjyaKPE8
      wHCQPOfeHT1rmQ09SPMcPbH/+DzKnwM99l/YPFggDT02gBk9C7KgPODfujwuegA9zrn9PD8iCT2E
      3qw81QeVPDmVkzyUiaQ85ZkXPWfslDz526g8ZFK9PAhp7TzR2bI826z5PPXhCD1MHBU9DBHyPG1P
      /Dwc8Rc9gcbNPIVitDznHJE8kC6NPLaqzDz+vBE9gN9qPMZtBj3Ynps87wZ+PM8TwDw+Swg92ohl
      PPAqlTxDQO088KEUPYJu9DwzzoA8UDapPNfvrzzUEfg8lstoPFeSvjwewIY8agScPGMktzw//Bo9
      wDXuPGzh/jzrkqI8dX+MPKXlvTyIHMI80rOHPJTzpjwlYhQ9Q0R4PA4rsDz+F488IlnBPILz7jwI
      MAk9tcYOPU9JlTyo8sA8KQzXPPm9czw6TO88hn2oPCP+uDy3CMg8nA26PCkfpjzAmhc9H44FPYju
      1zwrPAo9PxbSPCI9uDyRDBs9SsoEPWV3kTw=
  - 0
  - !!python/tuple
    - 1
    - 4
    - 40
  - !!python/tuple
    - 160
    - 40
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  seq_len: 4
