alphabet_size: 40
args: !!python/object:argparse.Namespace
  batch_size: 32
  ckpt_iterations: null
  cls_ckpt: null
  dropout: 0.1
  expand_simplex: true
  flow_type: argmax
  hidden_dim: 512
  limit_train_batches: 1000
  limit_val_batches: 1000
  max_epochs: 5000
  num_cnn_stacks: 5
  num_integration_steps: 10
  num_workers: 4
  prior_pseudocount: 2
  shuffle: false
  toy_num_cls: 1
  toy_seq_len: 4
  toy_simplex_dim: 40
num_cls: 1
toy_data: !!python/object:datasets.ToyDataset
  alphabet_size: 40
  class_probs: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCQAAADQ1Mjg2MTk2OHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADQ1Mjg2MTk2
      OHEBYS4BAAAAAAAAAAAAgD8=
  - 0
  - !!python/tuple
    - 1
  - !!python/tuple
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  max_samples: 512000
  num_cls: 1
  probs: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCQAAADQ3MDM3ODA2NHECWAMAAABjcHVxA0ugTnRxBFEugAJdcQBYCQAAADQ3MDM3ODA2
      NHEBYS6gAAAAAAAAAIdM7jwM0LI8CzvVPJgt1zxmmwk9/BzxPPBtDj1hXOc8TwSqPJ8vyTypYJA8
      Q1GaPBYj1jwBgw89OGe0PKikGj3lyJ487JiJPBG9yzxqsYQ8vQqaPO1aGT28ld88lHlzPBpuyDzl
      d4I8RQ6+PIvJ2zyA6Ls855GMPFR8uzxfTvA8yLATPUk51zzfx5w8sWR4PIC6Aj0+hMc8dzPdPO+G
      8zxMyYs8V1inPFxDIT16r988YwHxPAxltDy3UIY8Vh4cPQ2p7zyp7Mg8/pHPPCr0qDyRdL48g/7A
      PLm/7TzklZg8AHyGPBlb2jxm0Qk9ZACpPIgxuzz3b4k8ebH5PPPbCj32vbc8yWaFPLv6zzzFARw9
      UcmIPPji3DxOSr086AehPBwNzTzPpgE9hoCJPFp4kDwkCPc830W0PJZzCj1IoOo8cR2nPMBTGD1q
      5IE8KYfBPAj8Hz23z7Y8dJEgPZ72mzyke3c8KU4APclX4jz0x8c8cWy1PC/9qDy52rY8ToxuPPgn
      ijxQb9o8dx0XPRYIcjymtLM83L2RPJ7JuDxPBYw8sLt+PGWHBj3zB7o8DkYBPZRE6TyIGec8JtHc
      PL9I6Ty/NeQ8Sg0CPcG48jx6sdE8t926PF1j9TxlW7M8lALYPPvcrzzSsvI8AlOOPHRjDT28RKY8
      gSSZPDRb1zzcEQ49D+8DPeI7gzzJPxw9tNrRPHTJkjz8aNA8ZAbSPKT9uTy5s588/N3QPMW1qDyd
      tuY84haxPEuW8zw6cKY8wykQPQnmejxcKAc9OzO4PPIDCj3LUMU8KxO4PBXDwzxKquI8il0MPQJA
      AT33mZM8ZUQXPWywrDynfX48pP2TPJpycDw=
  - 0
  - !!python/tuple
    - 1
    - 4
    - 40
  - !!python/tuple
    - 160
    - 40
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  seq_len: 4
