alphabet_size: 40
args: !!python/object:argparse.Namespace
  batch_size: 32
  ckpt_iterations: null
  cls_ckpt: null
  dropout: 0.1
  expand_simplex: true
  flow_type: argmax
  hidden_dim: 512
  limit_train_batches: 1000
  limit_val_batches: 1000
  max_epochs: 5000
  num_cnn_stacks: 5
  num_integration_steps: 10
  num_workers: 4
  prior_pseudocount: 2
  shuffle: false
  toy_num_cls: 1
  toy_seq_len: 4
  toy_simplex_dim: 40
num_cls: 1
toy_data: !!python/object:datasets.ToyDataset
  alphabet_size: 40
  class_probs: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCgAAADExNjUzMDYxOTJxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAxMTY1MzA2
      MTkycQFhLgEAAAAAAAAAAACAPw==
  - 0
  - !!python/tuple
    - 1
  - !!python/tuple
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  max_samples: 512000
  num_cls: 1
  probs: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCgAAADExODYyNzk5NTJxAlgDAAAAY3B1cQNLoE50cQRRLoACXXEAWAoAAAAxMTg2Mjc5
      OTUycQFhLqAAAAAAAAAA7S3sPHsF9TxurBk955oQPSGctzwhxXE8cdd6PMK3gDyBV3U880mRPFZ6
      vDwA1/887s8TPTIQkjw783k8nTMDPe3Q1zxpGf48d1KPPHkODD2XZxI9+bi0PGX2DD3Gq+k8D2cd
      PWH+2zwDd7g8ewDTPHuTgDz5I8A8dZAEPW7QeDzR1IA8G8YaPYLLdjx3h3c8UyqrPGqliDz7j7c8
      NS0dPaIzvjx6XpU8MNPwPEqZCD2QmmU88oujPF1LDj05Z2s8VI2ePC36CD2AeJM8E4sUPbS9hjy+
      E6E8k4zhPAo5Dj0ZwRk9Yt8RPXTg3Dy8mn886RQOPRGrpjyEUpI8N66JPNPZ1zxRQPw8fLrOPOT3
      iDycexs9pSqMPJFmrjxpgt08hQsEPaI75zz9ewA9JmCMPHeo1DxxzH88J4mSPJuF/Tx7fBY9q57f
      PJJKmjzUThI9KBgPPdB5kTysv4E8zc8RPa8MiDxjWdc8buGoPKVAtTxUa4U8e1rZPB+SBD0mrQ89
      Q1uvPG8WfDwu0Is8ZL4QPZ8+Fj09ZfY8MGHwPMSR2jwCwOw85PyDPOgw2DwF8qM8APSxPPcRrjym
      2HY86vHNPBGzyDz5IKA8TcwZPY8FrzzKoYg8S3oQPV2AvjxgVIg867V7PND6aDxassI8k4vyPCWQ
      Aj3d/Ak92/HPPNxrwTx1+wE9j1DIPDcPvTwG08U85oLmPNJvwzxXeGs8PfK/PNip2zwNJnE8nByt
      PEXKBj30CvM8e5L2PH7zeTxophg9FLEVPcntnDyRjYE8QwJ8PGpl9jyrjqw87hYTPelT5Ty7P6o8
      /1CnPNwf9DwfiO08L3bzPN+wBT16kLc8t75wPA==
  - 0
  - !!python/tuple
    - 1
    - 4
    - 40
  - !!python/tuple
    - 160
    - 40
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  seq_len: 4
