alphabet_size: 40
args: !!python/object:argparse.Namespace
  batch_size: 32
  ckpt_iterations: null
  cls_ckpt: null
  dropout: 0.1
  expand_simplex: true
  flow_type: argmax
  hidden_dim: 512
  limit_train_batches: 1000
  limit_val_batches: 1000
  max_epochs: 5000
  num_cnn_stacks: 5
  num_integration_steps: 10
  num_workers: 4
  prior_pseudocount: 2
  shuffle: false
  toy_num_cls: 1
  toy_seq_len: 4
  toy_simplex_dim: 40
num_cls: 1
toy_data: !!python/object:datasets.ToyDataset
  alphabet_size: 40
  class_probs: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCQAAADkzOTUzNjU2MHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCQAAADkzOTUzNjU2
      MHEBYS4BAAAAAAAAAAAAgD8=
  - 0
  - !!python/tuple
    - 1
  - !!python/tuple
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  max_samples: 512000
  num_cls: 1
  probs: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCQAAADkxNDg1MzAwOHECWAMAAABjcHVxA0ugTnRxBFEugAJdcQBYCQAAADkxNDg1MzAw
      OHEBYS6gAAAAAAAAAB7nmTwBBBU9WKrYPHVlCz1Turo81l6nPE/m/Tzfd9o8WUMUPe6gkjzJDdI8
      9DfNPO/v2jxiA/Q8Hf6kPFyFuTzADSA9RpmmPJ7AiTyX2pA8CpqSPMakBj0uIJ08wJ+WPFeIjTz6
      B/c8/cWSPEcTpTxh3oY8UMoOPTxs9jw2PiI9v8WfPCza6TzHTew8mIbcPLYc9jxFRrI8mzyUPI1z
      ijxe8rs8C3KQPP7+4DyGA348NHSVPGff/zy95gY9PxIAPXA+sTwCbQM9Njx+PNZwoTy6Ms88aJD5
      POR9kDxHELE88eCAPPTbujy62dM8wo7QPJDPvjzXB/E8aM0JPY7kbjzxBcI897ERPeP3Fj0mNbE8
      4Q5pPFMtBj3Kg7U8k6UJPUv+kjwT5fw86n/aPFte8zwrT5s8DdvtPCEBjTztEhg93OScPG1DAj2a
      xbA895bnPFu24jyeHog8qK0VPQQ3DT3nsIQ83lWcPPlvCz0tXII8bVGsPOIphTxe3ac8+yuRPK8j
      Cz2uJLc8y2SKPHXLnTxb+hE9Xt6hPGqewTwg2sY8nHABPRxw6Dz2Rhk9BHrqPIYGFj2TqZw8om7R
      PAjNtjxdRe085577PDnInjy5atQ8tQTLPH0lgDythgs9f0+VPL6MCj1Rxx89ig8hPXOCBT2yObE8
      s8uLPNGPqzwZBbw8oW+hPOi6gDxtsyQ9XjGhPL7zyDxTFSE9EsqlPMFSwDzmZ4w8bUWRPCGkrDys
      VbY8KgUAPSYXoTxDgaE8e6kDPdWDiDzyciI9jTDTPNqhBD1nPAw9VW2EPPtW5TyiEJM8QPEQPZOM
      3TzGXY08l3t/PKvc4jxUL8c8W517PFLbejw=
  - 0
  - !!python/tuple
    - 1
    - 4
    - 40
  - !!python/tuple
    - 160
    - 40
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  seq_len: 4
